CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY, login VARCHAR(100), password_hash VARCHAR(255), role VARCHAR(30));
CREATE TABLE orders(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), phone VARCHAR(50), entrance VARCHAR(20), apartment VARCHAR(20), service VARCHAR(255), status VARCHAR(30));
